version = 1
SPDX-PackageName = "snapd-smoke-tests"
SPDX-PackageSupplier = "Zygmunt Krynicki <zygmunt.krynicki@canonical.com>"
SPDX-PackageDownloadLocation = "https://github.com/canonical/snapd-smoke-tests"
annotations = []
